project:
  type: book

book:
  title: "Introduction to Statistical Inference"
  subtitle: "STAT 201"
  author: 
    - "Marie Auger-Méthé"
    - "Melissa Lee"
    - "Rodolfo Lourenzutti"
  date: "2024-09-01"
  #cover-image: "hex-statistical-inference.png"
  repo-url: "https://github.com/Lourenzutti/statistical-inference"
  repo-branch: master
  repo-actions: [issue]
  sharing: [twitter, facebook]
  sidebar:
    logo: hex-statistical-inference.png
    style: floating
  chapters:
    - index.qmd
    - file: intro.qmd
      text: "Introduction"
    - file: sampling_distribution.qmd
      text: "Module 1: sampling distribution of parameter estimates"
    - file: bootstrap.qmd
      text: "Module 2: approximation of the sampling distribution via bootstrapping"
    - file: clt.qmd
      text: "Module 3: the central limit theorem and mathematical approximation of the sampling distribution"
    - file: interval_estimation_boot.qmd
      text: "Module 4: Confidence intervales via bootstrapping"
    - file: interval_estimation_dist.qmd
      text: "Module 5: Confidence intervals based on distributional assumptions"
    - file: hypothesis_testing_sim.qmd
      text: "Module 6: Hypothesis Testing via randomization"
    - file: hypothesis_testing_dist.qmd
      text: "Module 7: Hypothesis Testing based on distributional assumptions"
    - file: errors_in_inference.qmd
      text: "Module 8: Errors in inference"
    - file: ANOVA.qmd
      text: "Module 9: ANOVA and multiple hypothesis testing"
    - file: ab-testing.qmd
      text: "Module 10: A/B testing"
    
  page-footer: 
    center: "Copyright 2023, Rodolfo Lourenzutti -- Powered by Quarto" 
  open-graph: true
  


bibliography: references.bib

format:
  html:
    theme:
      light: simplex
    css: /style/main.scss
    toc: true
    html-math-method: katex
    smooth-scroll: true
    number-depth: 2
  pdf:
    documentclass: scrreprt
    
comments:
  hypothesis: true

filters:
  - webr